version: '3'
services:
  flask:
    build: 
          context: ./project
          dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./project:/project
    ports:
      - '10100:8080'
    command: python3 app.py
    